services:
  db:
    build:
      context: ./third-party
    image: MLRERAG/postgresql:pg_vector
    container_name: postgres-MLRERAG
    environment:
      POSTGRES_PASSWORD: LxJd5ouMt%|HVGXL
      POSTGRES_DB: MLRERAG
    ports:
      - 5433:5432
    networks:
      - MLRERAG_network
    volumes:
      - postgres_data:/var/lib/postgresql
    
  redis:
    image: redis:8.4.0-alpine
    container_name: redis-MLRERAG
    ports:
      - 6379:6379
    networks:
      - MLRERAG_network
    volumes:
      - redis_data:/data
  
  grobid:
    image: grobid/grobid:0.8.2.1-crf
    container_name: grobid-MLRERAG
    ports:
      - 8070:8070
    networks:
      - MLRERAG_network
  
  ollama:
    image: ollama/ollama
    container_name: ollama-MLRERAG
    ports:
      - 11435:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ollama_volume:/root/.ollama

volumes:
  postgres_data:
  redis_data:
  ollama_volume:

networks:
  MLRERAG_network:
    driver: bridge
    