services:

  rag:
    build:
      context: ./MLRERAG-RAG
    container_name: RAG-MLRERAG
    env_file:
      - ./MLRERAG-RAG/.env
    ports: 
      - 8002:8002
    networks:
      - MLRERAG_network
    depends_on:
      db:
        condition: service_started
      grobid:
        condition: service_started
      ollama:
        condition: service_started
      qdrant:
        condition: service_started
      neo4j:
        condition: service_healthy
  
  backend:
    build:
      context: ./MLRERAG-backend
    container_name: backend-MLRERAG
    env_file:
      - ./MLRERAG-backend/.env
    ports: 
      - 8000:8000
    networks:
      - MLRERAG_network
    depends_on:
      - rag
      - redis
  
  frontend:
    build:
      context: ./MLRERAG-frontend
    container_name: frontend-MLRERAG
    env_file:
      - ./MLRERAG-frontend/.env
    ports: 
      - 8501:8501
    networks:
      - MLRERAG_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  MLRERAG_network:
    driver: bridge