services:
  db:
    image: postgres:18.3-alpine
    container_name: postgres-MLRERAG
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RAG_USER=${RAG_USER}
      - RAG_PASSWORD=${RAG_PASSWORD}
      - BACKEND_USER=${BACKEND_USER}
      - BACKEND_PASSWORD=${BACKEND_PASSWORD}
    ports:
      - 5433:5432
    networks:
      - MLRERAG_network
    volumes:
      - ./init/postgres/init_roles.sh:/docker-entrypoint-initdb.d/init_roles.sh:ro
      - postgres_data:/var/lib/postgresql
    
  redis:
    image: redis:8.4.0-alpine
    container_name: redis-MLRERAG
    networks:
      - MLRERAG_network
    volumes:
      - redis_data:/data
  
  grobid:
    image: grobid/grobid:0.9.0-crf
    container_name: grobid-MLRERAG
    ports:
      - "7043:8070"
    networks:
      - MLRERAG_network
  
  ollama:
    image: ollama/ollama
    container_name: ollama-MLRERAG
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["/usr/bin/bash", "/init.sh"]
    networks:
      - MLRERAG_network
    volumes:
      - ollama_volume:/root/.ollama
      - ./init/ollama/init.sh:/init.sh
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-MLRERAG
    networks:
      - MLRERAG_network
    volumes:
      - qdrant_data:/qdrant/storage
  
  neo4j:
    image: neo4j:latest
    container_name: neo4j-MLRERAG
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_apoc_custom_procedures_enabled=true
    networks:
      - MLRERAG_network
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474/ || exit 1"]
      interval: 10s
      timeout: 5s   
      retries: 5     
      start_period: 20s

volumes:
  postgres_data:
  redis_data:
  ollama_volume:
  neo4j_data:
  neo4j_plugins:
  qdrant_data:

networks:
  MLRERAG_network:
    driver: bridge
    