name: Build and Publish Docker images

on:
  push:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      RAG_USER: ${{ secrets.RAG_USER }}
      RAG_PASSWORD: ${{ secrets.RAG_PASSWORD }}
      BACKEND_USER: ${{ secrets.BACKEND_USER }}
      BACKEND_PASSWORD: ${{ secrets.BACKEND_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create dummy .env
        run: touch .env

      - name: Build images
        run: docker compose -f docker-compose.services.yaml -f docker-compose.app.yaml build

      - name: Push images to GHCR
        run: docker compose -f docker-compose.services.yaml -f docker-compose.app.yaml push